# Generated by Django 6.0.1 on 2026-02-05 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="collection",
            name="products",
            field=models.ManyToManyField(blank=True, related_name="collections", to="api.product"),
        ),
    ]
