from pathlib import Path

path = Path('src/pages/CategoryPage.tsx')
text = path.read_text(encoding='utf-8')
start = text.index('\n  return (')
end = text.index('\n// Filter Content Component')
lines = [
"  return (",
"    <div className=\"min-h-screen bg-background\">",
"      <Header />",
"",
"      {/* Compact heading instead of full hero */}",
"      <section className=\"border-b border-border/50 bg-card/60\">",
"        <div className=\"container mx-auto px-4 py-8 md:py-10\">",
"          <nav className=\"mb-3 flex items-center gap-2 text-sm text-muted-foreground\">",
"            <Link to=\"/\" className=\"hover:text-primary\">Home</Link>",
"            <ChevronRight className=\"h-4 w-4\" />",
"            <Link to={`/category/${category.slug}`} className=\"hover:text-primary\">",
"              {category.name}",
"            </Link>",
"            {selectedSubcategory && (",
"              <>",
"                <ChevronRight className=\"h-4 w-4\" />",
"                <span className=\"text-foreground\">{selectedSubcategory.name}</span>",
"              </>",
"            )}",
"          </nav>",
"        </div>",
"      </section>",
"",
"      <section className=\"container mx-auto px-4 py-12\">",
"        <div className=\"grid gap-10 lg:grid-cols-[280px_1fr]\">",
"          {/* Desktop filters stay beside products */}",
"          <aside className=\"hidden lg:block sticky top-24 h-fit self-start\">",
"            <FilterContent",
"              priceRange={priceRange}",
"              setPriceRange={setPriceRange}",
"              priceBounds={priceBounds}",
"              allSizes={allSizes}",
"              selectedSizes={selectedSizes}",
"              toggleSize={toggleSize}",
"              availableFilters={availableFilters}",
"              isFilterSelected={isFilterSelected}",
"              toggleFilterOption={toggleFilterOption}",
"              isLoading={isLoading}",
"              clearFilters={clearFilters}",
"              showSizeFilter={showSizeFilter}",
"            />",
"          </aside>",
"",
"          <div className=\"space-y-10\">",
"            <div className=\"space-y-3 text-left max-w-5xl lg:max-w-6xl\">",
"              <motion.h1",
"                initial={{ opacity: 0, y: 10 }}",
"                animate={{ opacity: 1, y: 0 }}",
"                className=\"font-serif text-3xl font-bold md:text-4xl text-foreground\"",
"              >",
"                {heroName}",
"              </motion.h1>",
"              {heroDescription && (",
"                <motion.p",
"                  initial={{ opacity: 0, y: 10 }}",
"                  animate={{ opacity: 1, y: 0 }}",
"                  transition={{ delay: 0.05 }}",
"                  className=\"text-base leading-7 text-muted-foreground max-w-3xl\"",
"                >",
"                  {heroDescription}",
"                </motion.p>",
"              )}",
"              {showBedSizeFilter && linkedBedSize && (",
"                <motion.div",
"                  initial={{ opacity: 0, y: 10 }}",
"                  animate={{ opacity: 1, y: 0 }}",
"                  transition={{ delay: 0.1 }}",
"                  className=\"rounded-lg bg-primary/8 border border-primary/30 px-4 py-2 inline-block\"",
"                >",
"                  <p className=\"text-sm font-medium text-primary\">",
"                    Showing {linkedBedSize} size mattresses",
"                    <Link ",
"                      to={`/category/${slug}`}",
"                      className=\"ml-2 underline underline-offset-2 hover:no-underline\"",
"                    >",
"                      View all →",
"                    </Link>",
"                  </p>",
"                </motion.div>",
"              )}",
"            </div>",
"",
"            {/* Toolbar */}",
"            <div className=\"flex flex-col gap-4 md:flex-row md:items-center md:justify-between\">",
"              <p className=\"text-muted-foreground\">",
"                Showing {filteredProducts.length} of {allProducts.length} products",
"              </p>",
"",
"              <div className=\"flex flex-wrap items-center gap-4\">",
"                {/* Mobile Filter Toggle */}",
"                <Button",
"                  variant=\"outline\"",
"                  onClick={() => setIsFilterOpen(!isFilterOpen)}",
"                  className=\"gap-2 border-accent lg:hidden\"",
"                >",
"                  <SlidersHorizontal className=\"h-4 w-4\" />",
"                  Filters",
"                </Button>",
"",
"                {/* Sort */}",
"                <Select value={sortBy} onValueChange={setSortBy}>",
"                  <SelectTrigger className=\"w-48 border-accent\">",
"                    <SelectValue placeholder=\"Sort by\" />",
"                  </SelectTrigger>",
"                  <SelectContent>",
"                    <SelectItem value=\"featured\">Featured</SelectItem>",
"                    <SelectItem value=\"price-low\">Price: Low to High</SelectItem>",
"                    <SelectItem value=\"price-high\">Price: High to Low</SelectItem>",
"                    <SelectItem value=\"rating\">Highest Rated</SelectItem>",
"                    <SelectItem value=\"newest\">Newest</SelectItem>",
"                  </SelectContent>",
"                </Select>",
"              </div>",
"            </div>",
"",
"            {/* Mobile Filters */}",
"            {isFilterOpen && (",
"              <motion.div",
"                initial={{ opacity: 0 }}",
"                animate={{ opacity: 1 }}",
"                exit={{ opacity: 0 }}",
"                className=\"fixed inset-0 z-50 bg-espresso/50 backdrop-blur-sm lg:hidden\"",
"                onClick={() => setIsFilterOpen(false)}",
"              >",
"                <motion.div",
"                  initial={{ x: '-100%' }}",
"                  animate={{ x: 0 }}",
"                  exit={{ x: '-100%' }}",
"                  onClick={(e) => e.stopPropagation()}",
"                  className=\"h-full w-80 overflow-y-auto bg-background p-6\"",
"                >",
"                  <div className=\"mb-6 flex items-center justify-between\">",
"                    <h3 className=\"font-serif text-xl font-semibold\">Filters</h3>",
"                    <button onClick={() => setIsFilterOpen(false)}>",
"                      <X className=\"h-5 w-5\" />",
"                    </button>",
"                  </div>",
"                  <FilterContent",
"                    priceRange={priceRange}",
"                    setPriceRange={setPriceRange}",
"                    priceBounds={priceBounds}",
"                    allSizes={allSizes}",
"                    selectedSizes={selectedSizes}",
"                    toggleSize={toggleSize}",
"                    availableFilters={availableFilters}",
"                    isFilterSelected={isFilterSelected}",
"                    toggleFilterOption={toggleFilterOption}",
"                    isLoading={isLoading}",
"                    clearFilters={clearFilters}",
"                    showSizeFilter={showSizeFilter}",
"                  />",
"                </motion.div>",
"              </motion.div>",
"            )}",
"",
"            {/* Products Grid */}",
"            <div className=\"flex-1\">",
"              {filteredProducts.length === 0 ? (",
"                <div className=\"flex min-h-[300px] items-center justify-center rounded-lg bg-card\">",
"                  <div className=\"text-center\">",
"                    <p className=\"mb-4 text-lg text-muted-foreground\">",
"                      No products match your filters",
"                    </p>",
"                    <Button onClick={clearFilters} variant=\"outline\">",
"                      Clear Filters",
"                    </Button>",
"                  </div>",
"                </div>",
"              ) : (",
"                <div className=\"grid gap-6 sm:grid-cols-2 xl:grid-cols-3\">",
"                  {filteredProducts.map((product, index) => (",
"                    <ProductCard ",
"                      key={product.id} ",
"                      product={product} ",
"                      index={index}",
"                      fromBedProduct={linkedBedProduct}",
"                      selectedBedSize={linkedBedSize}",
"                    />",
"                  ))}",
"                </div>",
"              )}",
"            </div>",
"          </div>",
"        </div>",
"      </section>",
"",
"      <Footer />",
"    </div>",
"  );",
]
new_block = '\n'.join(lines)
new_text = text[:start] + '\n' + new_block + '\n' + text[end:]
path.write_text(new_text, encoding='utf-8')
print('updated')
